#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git goimports pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' | grep -v -e "^vendor/")
[ -z "$gofiles" ] && exit 0

unformatted=$(goimports -l $gofiles)
if [ -z "$unformatted" ]; then
    make check
    [ "$?" -ne 0 ] && echo "Please fix these errors before commit." && exit 2

    make lint
    [ "$?" -ne 0 ] && echo "Please fix these errors before commit." && exit 2

    exit 0
fi

# goimports is included in gometalinter, but we want to provide specific commands to fix
# Some files are not goimports'd. Print message and fail.

echo >&2 "Go files must be formatted with goimports. Please run:"
echo >&2 "  goimports -w ${unformatted//$'\n'/ }"

exit 1
